#!/usr/bin/env bash

SRC="$HOME/Downloads"

for file in "$SRC"/*; do

    [[ -f "$file" ]] || continue

    if [[ "$file" == *.txt || "$file" == *.md || "$file" == *.doc ]]; then
        mkdir -p "$SRC/Textfiles"
        mv "$file" "$SRC/Textfiles"

        elif [[ "$file" == *.png || "$file" == *.jpg || "$file" == *.raw ]]; then 
        mkdir -p "$SRC/Images"
        mv "$file" "$SRC/Images"
    
    elif [[ "$file"  == *.avi || "$file" == *.wmv || "$file" == *.mp4 ]]; then 
        mkdir -p "$SRC/Videos"
        mv "$file" "$SRC/Videos"

    elif [[ "$file" == *.pdf ]]; then 
        mkdir -p "$SRC/PDFs"
        mv "$file" "$SRC/PDFs"

    elif [[ "$file" == *.pptx ]]; then
        mkdir -p "$SRC/Presentations"
        mv "$file" "$SRC/Presentations"

    elif [[ "$file" == *.wav || "$file" == *.mp3 ]]; then
        mkdir -p "$SRC/Sound_files"
        mv "$file" "$SRC/Sound_files"

    else
        mkdir -p "$SRC/Misc_unknown_file_types"
        mv "$file" "$SRC/Misc_unknown_file_types"
    fi
done






